### ISSUE TITLE
Complete About Page

### ISSUE THREAD

**Issue by cjswayne** [jman2476/Moo-Journal#15]
DONT FORGET TO OPEN A NEW BRANCH AND COMMIT A BUNCH

[https://www.loom.com/share/05b7cdba1b854f6cbd4d52358cd0f300?sid=d81bb31f-9616-47da-84a0-2d3c49a2a4aa](https://www.loom.com/share/05b7cdba1b854f6cbd4d52358cd0f300?sid=d81bb31f-9616-47da-84a0-2d3c49a2a4aa)

Add a about excerpt explaing the 'id' of the project, and anything else you want to include. Style scss as per necessary.

**Comment by cjswayne** [comment]
@Wintino5 @jsaini1727 -- whoever wants to do this task unassign the other person when u start it please and thank you.

**Comment by jsaini1727** [comment]
Wrote a few lines inspiring users to start journaling with us.
