### ISSUE TITLE
Consolidate Components imports in app.jsx

### ISSUE THREAD

**Issue by cjswayne** [jman2476/Moo-Journal#23]
[https://www.loom.com/share/c59b05a00a2548afa4054a0a30afcfcd?sid=0f0a933b-6892-458f-891b-813fde82377e](https://www.loom.com/share/c59b05a00a2548afa4054a0a30afcfcd?sid=0f0a933b-6892-458f-891b-813fde82377e)

This task should be done after [this task](https://github.com/jman2476/Moo-Journal/issues/20) has been completed first. 

An example of consolidation looks like: 

From this:
`
import Homepage from './pages/Homepage'
// other imports
`
to this: 
`import { Homepage, AboutPage, LoginPage, MyMooJournalPage, NewJournalEntryPage, SignUpPage } from './pages';`

**Comment by jsaini1727** [comment]
Completed the import consolidation
